version: "3"

networks:
  hadoop_net:
    external: true

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ../conf/hadoop/core-site.xml:/etc/hadoop/core-site.xml
      - ../conf/hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ../conf/hadoop/mapred-site.xml:/etc/hadoop/mapred-site.xml
      - ../conf/hadoop/yarn-site.xml:/etc/hadoop/yarn-site.xml
    environment:
      - CLUSTER_NAME=docker-big-data
    networks:
      - hadoop_net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    hostname: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ../conf/hadoop/core-site.xml:/etc/hadoop/core-site.xml
      - ../conf/hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ../conf/hadoop/mapred-site.xml:/etc/hadoop/mapred-site.xml
      - ../conf/hadoop/yarn-site.xml:/etc/hadoop/yarn-site.xml
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - "9864:9864"
    networks:
      - hadoop_net

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    hostname: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    volumes:
      - ../conf/hadoop/core-site.xml:/etc/hadoop/core-site.xml
      - ../conf/hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ../conf/hadoop/mapred-site.xml:/etc/hadoop/mapred-site.xml
      - ../conf/hadoop/yarn-site.xml:/etc/hadoop/yarn-site.xml
    ports:
      - "8088:8088"
    networks:
      - hadoop_net

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager1
    restart: always
    hostname: nodemanager1
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - ../conf/hadoop/core-site.xml:/etc/hadoop/core-site.xml
      - ../conf/hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ../conf/hadoop/mapred-site.xml:/etc/hadoop/mapred-site.xml
      - ../conf/hadoop/yarn-site.xml:/etc/hadoop/yarn-site.xml
    ports:
      - "18040:8040"
      - "18041:8041"
      - "18042:8042"
    networks:
      - hadoop_net

  nodemanager2:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager2
    restart: always
    hostname: nodemanager2
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - ../conf/hadoop/core-site.xml:/etc/hadoop/core-site.xml
      - ../conf/hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ../conf/hadoop/mapred-site.xml:/etc/hadoop/mapred-site.xml
      - ../conf/hadoop/yarn-site.xml:/etc/hadoop/yarn-site.xml
    ports:
      - "28040:8040"
      - "28041:8041"
      - "28042:8042"
    networks:
      - hadoop_net

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    hostname: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
      - ../conf/hadoop/core-site.xml:/etc/hadoop/core-site.xml
      - ../conf/hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ../conf/hadoop/mapred-site.xml:/etc/hadoop/mapred-site.xml
      - ../conf/hadoop/yarn-site.xml:/etc/hadoop/yarn-site.xml
    networks:
      - hadoop_net

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver: