version: "3"

networks:
  hadoop_net:
    external: true

services:
  flink-1.13.3:
    image: flink:1.13.3-scala_2.12-java8
    container_name: flink-1.13.3
    restart: always
    ports:
      - "8081:8081"
    networks:
      - hadoop_net